package:
  name: wcsaxes
  version: "{{version}}"

source:
  fn: wcsaxes-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/g/wcsaxes/wcsaxes-{{version}}.tar.gz
  md5: {{md5}}
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wcsaxes = wcsaxes:main
    #
    # Would create an entry point called wcsaxes that calls wcsaxes.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - astropy

  run:
    - python
    - matplotlib
    - astropy

test:
  # Python imports
  imports:
    - wcsaxes

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://wcsaxes.readthedocs.org
  license: BSD License
  summary: 'WCSAxes: a framework for plotting astronomical and geospatial data'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
